### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#2374]
After build site:

```sh
htmlproofer --assume-extension .
```

- [ ] ./EIPS/eip-1.html
  *  External link https://gitter.im/ethereum/topics failed: 404 No error
- [ ] ./EIPS/eip-1077.html
  *  External link https://github.com/uport-project/uport-identity/blob/develop/docs/txRelay.md failed: 404 No error
- [ ] ./EIPS/eip-1123.html
  *  External link https://github.com/ethpm/ethpm-spec/tree/v2.0.0/spec/package.spec.json failed: 404 No error
- [ ] ./EIPS/eip-1202.html
  *  External link https://github.com/xinbenlv/eip-1202-draft/blob/master/contracts/advanced-version/AdvancedTokenVote1202.sol failed: 404 No error
  *  External link https://github.com/xinbenlv/eip-1202-draft/blob/master/contracts/simple-version/SimplestVote1202.sol failed: 404 No error
  *  External link https://github.com/xinbenlv/eip-1202-draft/blob/master/contracts/simple-version/TokenVote1202.sol failed: 404 No error
- [ ] ./EIPS/eip-1271.html
  *  External link https://etherdelta.com/ failed: 503 No error
- [ ] ./EIPS/eip-1474.html
  *  External link https://cpp-ethereum.org failed: got a time out (response code 0)
- [ ] ./EIPS/eip-1484.html
  *  External link https://decentralized.id/ failed: got a time out (response code 0)
- [ ] ./EIPS/eip-1581.html
  *  External link https://https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- [ ] ./EIPS/eip-1588.html
  *  External link https://github.com/naikmyeong failed: 404 No error
- [ ] ./EIPS/eip-1620.html
  *  External link http://chronosprotocol.org/chronos-white-paper.pdf failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- [ ] ./EIPS/eip-1767.html
  *  External link https://github.com/PegaSysEng/pantheon/blob/master/CHANGELOG.md#111 failed: 404 No error
- [ ] ./EIPS/eip-1775.html
  *  External link http://docs.ens.domains/en/latest/implementers.html#namehash failed: 404 No error
- [ ] ./EIPS/eip-190.html
  *  External link https://github.com/eris-ltd/eris-cli failed: 404 No error
- [ ] ./EIPS/eip-1901.html
  *  External link https://github.com/etclabscore/ECIPs/blob/master/ECIPs/ECIP-1053.md failed: 404 No error
- [ ] ./EIPS/eip-1967.html
  *  External link https://github.com/aragon/aragonOS/blob/dev/contracts/common/DelegateProxy.sol failed: 404 No error
- [ ] ./EIPS/eip-2003.html
  *  External link https://ethereum.github.io/evmc/structevmc__instance.html#a0823ebff21f9b0395b157e8c6b14a207 failed: 404 No error
  *  External link https://ethereum.github.io/evmc/structevmc__instance.html#ae63b9ca898aa41cbd1e2fe86ca8f4e1c failed: 404 No error
- [ ] ./EIPS/eip-616.html
  *  External link https://library.aceondo.net/ebooks/Computer_Science/algorithm-the_art_of_computer_programming-knuth.pdf failed: 500 No error
- [ ] ./EIPS/eip-725.html
  *  External link https://github.com/gnosis/safe-contracts/blob/master/contracts/Enum.sol#L7 failed: 404 No error
- [ ] ./EIPS/eip-884.html
  *  External link https://legis.delaware.gov/json/BillDetail/GenerateHtmlDocument?legislationId=25730&legislationTypeId=1&docTypeId=2&legislationName=SB69 failed: got a time out (response code 0)
- [ ] ./EIPS/eip-897.html
  *  External link https://github.com/aragon/aragonOS/blob/dev/contracts/apps/AppProxyPinned.sol failed: 404 No error
  *  External link https://github.com/aragon/aragonOS/blob/dev/contracts/apps/AppProxyUpgradeable.sol failed: 404 No error
  *  External link https://github.com/aragon/aragonOS/blob/dev/contracts/kernel/KernelProxy.sol failed: 404 No error
- [ ] ./EIPS/eip-900.html
  *  External link https://github.com/maticnetwork/contracts/blob/master/contracts/StakeManager.sol failed: 404 No error
- [ ] ./EIPS/eip-902.html
- [ ] ./EIPS/eip-908.html
  *  External link https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ# failed: got a time out (response code 0)
- [ ] ./EIPS/eip-969.html
  *  External link https://gitter.im/ethereum/topics/topic/5ac4d974109bb043328911ce/eip-969-discussion failed: 404 No error
- [ ] ./EIPS/eip-999.html
  *  External link https://github.com/paritytech/parity/compare/a5-eip999-poc failed: 404 No error
- [x] ./erc.html
  *  External link https://github.com/pizza_r0b failed: 404 No error
htmlproofer 3.10.2 | Error:  HTML-Proofer found 92 failures!

**Comment by axic** [comment]
I don't think there's anything what can be done here.

**Comment by axic** [comment]
This is the current status:
```
- ./_site/EIPS/eip-1.html
  *  External link https://gitter.im/ethereum/topics failed: 404 No error
- ./_site/EIPS/eip-1057.html
  *  External link https://leastauthority.com/static/publications/Least%20Authority%20-%20ProgPow%20Algorithm%20Final%20Audit%20Report.pdf failed: 404 No error
- ./_site/EIPS/eip-1077.html
  *  External link https://github.com/uport-project/uport-identity/blob/develop/docs/txRelay.md failed: 404 No error
- ./_site/EIPS/eip-1191.html
  *  External link https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/utils/formatters.ts#L126 failed: 404 No error
- ./_site/EIPS/eip-1202.html
  *  External link https://blog.enigma.co/private-voting-for-tcrs-with-enigma-b441b5d4fa7b failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
  *  External link https://github.com/xinbenlv/eip-1202-draft/blob/master/contracts/advanced-version/AdvancedTokenVote1202.sol failed: 404 No error
  *  External link https://github.com/xinbenlv/eip-1202-draft/blob/master/contracts/simple-version/SimplestVote1202.sol failed: 404 No error
  *  External link https://github.com/xinbenlv/eip-1202-draft/blob/master/contracts/simple-version/TokenVote1202.sol failed: 404 No error
  *  External link https://wiki.aragon.org/dev/apps/voting/ failed: 404 No error
- ./_site/EIPS/eip-1474.html
  *  External link https://cpp-ethereum.org/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't connect to server
- ./_site/EIPS/eip-1484.html
  *  External link https://decentralized.id/ failed: got a time out (response code 0)
- ./_site/EIPS/eip-1504.html
  *  External link https://gist.github.com/swordghost/77c96a972106af6ec6ccea9c2d66e768 failed: 404 No error
  *  External link https://gist.github.com/swordghost/969648793ed54fdf027cb6df1b894b75 failed: 404 No error
- ./_site/EIPS/eip-1581.html
  *  External link https://https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- ./_site/EIPS/eip-1620.html
  *  External link http://chronosprotocol.org/chronos-white-paper.pdf failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- ./_site/EIPS/eip-1767.html
  *  External link https://github.com/PegaSysEng/pantheon/blob/master/CHANGELOG.md#111 failed: 404 No error
- ./_site/EIPS/eip-1822.html
  *  External link https://medium.com/terminaldotco/escape-hatch-proxy-efb681de108d failed: 410 No error
- ./_site/EIPS/eip-190.html
  *  External link https://github.com/eris-ltd/eris-cli failed: 404 No error
- ./_site/EIPS/eip-1901.html
  *  External link https://github.com/etclabscore/ECIPs/blob/master/ECIPs/ECIP-1053.md failed: 404 No error
- ./_site/EIPS/eip-1967.html
  *  External link https://github.com/windingtree/upgradeable-token-labs/blob/af3b66096091d8282d5c9c55c33365315d85f3e1/contracts/upgradable/DelegateProxy.sol failed: 404 No error
- ./_site/EIPS/eip-2003.html
  *  External link https://ethereum.github.io/evmc/structevmc__instance.html#a0823ebff21f9b0395b157e8c6b14a207 failed: 404 No error
  *  External link https://ethereum.github.io/evmc/structevmc__instance.html#ae63b9ca898aa41cbd1e2fe86ca8f4e1c failed: 404 No error
- ./_site/EIPS/eip-2255.html
  *  External link https://github.com/MetaMask/metamask-extension/tree/LoginPerSite failed: 404 No error
- ./_site/EIPS/eip-2304.html
  *  External link https://discuss.ens.domains/t/new-standard-proposal-ens-multicoin-support/1148 failed: 404 No error
- ./_site/EIPS/eip-615.html
  *  External link https://static.docs.arm.com/100076/0100/arm_instruction_set_reference_guide_100076_0100_00_en.pdf failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Peer certificate cannot be authenticated with given CA certificates
- ./_site/EIPS/eip-616.html
  *  External link https://library.aceondo.net/ebooks/Computer_Science/algorithm-the_art_of_computer_programming-knuth.pdf failed: 500 No error
- ./_site/EIPS/eip-712.html
  *  External link https://web3js.readthedocs.io/en/1.0/index.html failed: 404 No error
- ./_site/EIPS/eip-725.html
  *  External link https://github.com/ERC725Alliance/erc725/tree/master/contracts/contracts failed: 404 No error
  *  External link https://github.com/gnosis/safe-contracts/blob/master/contracts/Enum.sol#L7 failed: 404 No error
- ./_site/EIPS/eip-900.html
  *  External link https://github.com/maticnetwork/contracts/blob/master/contracts/StakeManager.sol failed: 404 No error
- ./_site/EIPS/eip-908.html
  *  External link https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ# failed: 404 No error
- ./_site/EIPS/eip-969.html
  *  External link https://gitter.im/ethereum/topics/topic/5ac4d974109bb043328911ce/eip-969-discussion failed: 404 No error
- ./_site/EIPS/eip-999.html
  *  External link https://github.com/paritytech/parity/compare/a5-eip999-poc failed: 404 No error
- ./_site/all.html
  *  External link https://github.com/naikmyeong failed: 404 No error
  *  External link https://github.com/uriklarman failed: 404 No error
htmlproofer 3.15.3 | Error:  HTML-Proofer found 35 failures!
```

Still I think there's nothing to be done about this and suggest to close the issue.

**Comment by fulldecent** [comment]
Fair recommendation
