### ISSUE TITLE
Close issues that are duplicates of an existing EIP

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5111]
Since apparently at least 3 propoals are a duplicate of one another, and (multiple!) existing EIPs, I will cease to comment/ping Micah for each one, and instead list them below as I find them:

- [x] #223 duplicate of https://eips.ethereum.org/EIPS/eip-4524 and https://eips.ethereum.org/EIPS/eip-1363
- [x] #677 duplicate of https://eips.ethereum.org/EIPS/eip-4524 and https://eips.ethereum.org/EIPS/eip-1363
- [x] #827 duplicate of https://eips.ethereum.org/EIPS/eip-4524 and https://eips.ethereum.org/EIPS/eip-1363

In addition, the following proposals are actually merged in the EIP repo, and should probably be closed:

- [x] #861
- [x] #998
- [x] #1121
- [x] #1155
- [x] #1202
- [x] #1271
- [x] #1319
- [x] #1930
- [x] #2125
- [x] #2135
- [x] #2228
- [x] #2255

The following proposals have been superseded by a more generic standard:

- [x] #865 by https://eips.ethereum.org/EIPS/eip-2771

**Comment by Pandapip1** [comment]
One last @MicahZoltu

**Comment by MicahZoltu** [comment]
Taken care of.  Thanks for digging all of these up!
