### ISSUE TITLE
SoulWallet

### ISSUE THREAD

**Issue by BigBro17on25tolife** [ethereum/EIPs#7333]
DOAstep
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/EIPs/pull/7276
- [ ] https://github.com/ethereum/EIPs/pull/7336
- [ ] https://github.com/ethereum/EIPs/pull/7331
```

**Comment by Pandapip1** [comment]
This is not the correct place to track your EIPs. Please create a GitHub project in your own org and track it there.
