### ISSUE TITLE
Separate EIPs and ERCs

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#8284]
### Proposed Change

The README.md file in this repo links to a closed PR and states that ERCs have been separated from EIPs.

In fact, the separation has only been started and more work remains to be done. This issue serves as a place to discuss and track the remaining project management work to do.

# Work plan

- [ ] Update README.md to say that the separation is "in progress" and link to this issue instead of that merge request.
- [ ] Clearly decide which ones are ERCs and getting migrated. This should not be difficult. But it is a check-offable thing.

Update other repo

- [ ] Turn on GitHub Pages builds for the ERCs repository with the hostname ercs.ethereum.org
- [ ] Link to this URL from the "repo info" for the ERCs repo, i.e. the notes on the right when you visit it on GitHub
- [ ] Update ercs.ethereum.org use the GitHub Pages DNSI A records
- [ ] Update the ERCs website / [draft PR](https://github.com/ethereum/EIPs/pull/6483)
  - [ ] New RSS feed
  - [ ] New webpage content

Update this repo

- [ ] Remove ERCs
- [ ] Update descriptions for EIP categories, now is the time, hasn't been done in 10 years
- [ ] Update website to focus on just the EIPs
- [ ] Update RSS feeds

Cross promote

- [ ] Cross link both websites
- [ ] Cross promote both RSS feeds to each other
- [ ] Draft an announcement and recommend to the owner of the Ethereum.org blog that they post it
- [ ] Draft an announcement and recommend to the owner of the Ethereum X account that they post it

---

See also: prior discussion at: https://github.com/ethereum/EIPs/pull/7206

**Comment by fulldecent** [comment]
I can help with some of these things. But again. I need green lights and commitment to merge, from people with merge access, and a clear indication from them what are the hurdles achieve merge.

**Comment by fulldecent** [comment]
@xinbenlv @poojaranjan

**Comment by xinbenlv** [comment]
Yes we wanna do this direction! Item-wise, lets put it in EIPIP meeting and go through task lists to sanity check.

**Comment by lightclient** [comment]
bit of a dup of https://github.com/ethereum/ERCs/issues/8

**Comment by fulldecent** [comment]
https://github.com/ethereum/ERCs/issues/8 discusses how individual authors can move their pull request to a new repo.

This issue is a separate concern of how to make the ERCs' project and community great like the EIPs' is.

**Comment by Eianaftyio** [comment]
.update

**Comment by SamWilsn** [comment]
If you're okay waiting an unspecified amount of time, I think most of these points are already taken care of in my [working groups demo](https://github.com/eips-wg/) ([preview](https://eips.fyi/)).
