### ISSUE TITLE
Asset futures spot walet my ful  

### ISSUE THREAD

**Issue by Vencaq** [ethereum/EIPs#8805]
### Pull Request

"2011 International Joint Conference on Neural Networks," in IEEE Transactions on Neural Networks, vol. 21, no. 8, pp. 1378-1378, Aug. 2010, doi: 10.1109/TNN.2010.2063350. Abstract: Provides a listing of upcoming conference events of interest to practitioners and researchers. URL: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5536934&isnumber=5536895

### What happened?

42 Charlemont Street, Dublin, Ireland, D02 VN88

### Relevant log output

```shell
vaclavkrajcovic2.cb.id btc etherum bnb eth usdt
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/EIPs/pull/8629
- [x] vaclavkrajcovic2.cb.id btc etherum bnb eth usdt
- [ ] https://github.com/ethereum/EIPs/pull/8802
- [ ] https://github.com/ethereum/EIPs/pull/8740
- [ ] https://github.com/ethereum/EIPs/pull/8377
- [ ] https://github.com/ethereum/EIPs/pull/8569
- [ ] https://github.com/ethereum/EIPs/pull/8803
- [ ] https://github.com/ethereum/EIPs/issues/8801
- [ ] https://github.com/ethereum/EIPs/pull/8691
- [ ] https://github.com/ethereum/EIPs/pull/8769
- [ ] https://github.com/ethereum/EIPs/pull/8799
- [ ] https://github.com/ethereum/EIPs/issues/8800
- [ ] https://github.com/ethereum/EIPs/pull/8630
- [ ] https://github.com/ethereum/EIPs/pull/8616
- [ ] https://github.com/ethereum/EIPs/pull/8611
- [ ] https://github.com/ethereum/EIPs/issues/8282
- [ ] https://github.com/ethereum/EIPs/pull/8785
- [ ] https://github.com/ethereum/EIPs/pull/8797
- [ ] https://github.com/ethereum/EIPs/pull/8796
- [ ] https://github.com/ethereum/EIPs/pull/8609
- [ ] https://github.com/ethereum/EIPs/pull/2728
- [ ] https://github.com/ethereum/EIPs/pull/1368
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/EIPs/issues/8804
```

**Comment by Vencaq** [comment]
@Vencaq

**Comment by Vencaq** [comment]
Paysafe
